### ISSUE TITLE
add support for more firmware versions

### ISSUE THREAD

**Issue by eriu** [digineo/gluon-autoflasher#7]
getestete Versionen:

* TL-WR1043ND-V1
  * http://www.tp-link.de/download/TL-WR1043ND_V1.html#Firmware
  * 3.13.13 Build 130428 Rel.58290n (from 25/03/13) -> status: x (not working)
    * [wr1043-v1-130428.html.txt](https://github.com/digineo/gluon-autoflasher/files/76237/wr1043-v1-130428.html.txt)
    * IP adress: 192.168.1.1
    * cookie: -
    
		      ./autoflash
		      Waiting for 192.168.1.1 ... ✓
		      Traceback (most recent call last):
		      File "./autoflash", line 8, in <module>
		      autoflasher.Run()
		      File "lib/autoflasher.py", line 175, in Run
		      AutoFlasher("192.168.1.1")
		      File "lib/autoflasher.py", line 116, in __init__
		      self.authorize()
		      File "lib/autoflasher.py", line 146, in authorize
		      raise RuntimeError("Unable to extract session_id")
		      RuntimeError: Unable to extract session_id
  * 3.13.15 Build 140319 Rel.41339n (from 19/03/14) -> status: x (not working)
  	* [wr1043-v1-140319.html.txt](https://github.com/digineo/gluon-autoflasher/files/76238/wr1043-v1-140319.html.txt)
    * IP Adress: 192.168.1.1
    * cookie: Basic%20YWRtaW46YWRtaW4%3D
    
		      ./autoflash
		      Waiting for 192.168.1.1 ... ✓
		      Traceback (most recent call last):
		      File "./autoflash", line 8, in <module>
		        autoflasher.Run()
		        File "lib/autoflasher.py", line 175, in Run
		      AutoFlasher("192.168.1.1")
		        File "lib/autoflasher.py", line 116, in __init__
		      self.authorize()
		        File "lib/autoflasher.py", line 146, in authorize
		      raise RuntimeError("Unable to extract session_id")
		      RuntimeError: Unable to extract session_id

  * TP-Link TL-WR1043ND v2
    * http://www.tp-link.de/download/TL-WR1043ND_V2.html#Firmware
    * wr1043v2_en_3_15_30_up_boot(140912).bin stripped
    * 3.15.30 Build 140912 Rel.66929n -> status: x (not working)
      * [wr1043-v2-140912.html.txt](https://github.com/digineo/gluon-autoflasher/files/76239/wr1043-v2-140912.html.txt)
      * IP Adress: http://192.168.0.1/
      * cookie:  -
      
		    ./autoflash
			Waiting for 192.168.0.1 ... ✓
			Fetching model ... Traceback (most recent call last):
		 		File "./autoflash", line 8, in <module>
		    autoflasher.Run()
		  File "lib/autoflasher.py", line 175, in Run
		    AutoFlasher("192.168.0.1")
		  File "lib/autoflasher.py", line 119, in __init__
		    self.model = ExtractModel(self.request("status", "menu").text)
		  File "lib/autoflasher.py", line 52, in ExtractModel
		    raise UnsupportedModel("Unsupported model: %s" % model)
			autoflasher.UnsupportedModel: Unsupported model: WR1043 v2
		
  * 3.19.32 Build 150717 Rel.53114n (from 11/08/15) -> status: ✓ (works)
  	* [wr1043-v2-150707.html.txt](https://github.com/digineo/gluon-autoflasher/files/76240/wr1043-v2-150707.html.txt)
    * IP Adress: http://192.168.0.1/
    * cookie: Basic%20YWRtaW46MjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzM%3D
    		
    		./autoflash
			Waiting for 192.168.0.1 ... ✓
			Fetching model ... tp-link-tl-wr1043n-nd-v2
			Downloading http://firmware.md.freifunk.net/stable/LATEST/factory/gluon-ffmd-0.33-tp-link-tl-wr1043n-nd-v2.bin .................................. ✓
			Uploading image ...  ✓
			Flashing ...  ✓
			Waiting for 192.168.1.1 ....................................................................................... ✓
  * 3.19.32 Build 150910 Rel.44072n (from 23/10/15) -> status: ✓ (works)
  	* [wr1043-v2-150910.html.txt](https://github.com/digineo/gluon-autoflasher/files/76241/wr1043-v2-150910.html.txt)
    * IP Adress: http://192.168.0.1/
    * cookie: Basic%20YWRtaW46MjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzM%3D
    
		    ./autoflash
			Waiting for 192.168.0.1 ... ✓
			Fetching model ... tp-link-tl-wr1043n-nd-v2
			Uploading image ...  ✓
			Flashing ...  ✓
			Waiting for 192.168.1.1 ....................................................................................... ✓

**Comment by eriu** [comment]
wr1043nd-v1 mit 3.13.13 Build 130428 Rel.58290n:
 curl "http://192.168.1.1/userRpm/LoginRpm.htm?Save=Save" -b "Authorization=Basic%20YWRtaW46YWRtaW4%3D" > wr143v1-130428-Login.html.txt

extrahierte LoginRpm:
[wr143v1-130428-Login.html.txt](https://github.com/digineo/gluon-autoflasher/files/76294/wr143v1-130428-Login.html.txt)

**Comment by eriu** [comment]
curl "http://192.168.1.1/" -b "Authorization=Basic%20YWRtaW46YWRtaW4%3D" > save.html.txt
[save.html.txt](https://github.com/digineo/gluon-autoflasher/files/76295/save.html.txt)

**Comment by eriu** [comment]
after https://github.com/digineo/gluon-autoflasher/commit/0277925d1523fb99b03c88e17ba7a35372aa1cb8
TL-WR1043 V1 works, so we can close https://github.com/digineo/gluon-autoflasher/issues/7
* 3.13.13 Build 130428 Rel.58290n -> status: ✓ (works)
* 3.13.15 Build 140319 Rel.41339n -> status: ✓ (works)
